"""Buyer intent and proposed offer models."""
from __future__ import annotations

from typing import List, Literal, Optional
from pydantic import BaseModel, Field


class BuyerIntent(BaseModel):
    """Structured buyer negotiation intent received from user/client."""

    sku: str = Field(..., description="Target SKU identifier")
    quantity: int = Field(..., gt=0, description="Requested purchase quantity")
    target_price: Optional[float] = Field(
        None, gt=0, description="Buyer's target or suggested unit price in INR"
    )
    urgency: Literal["high", "normal"] = Field(
        default="normal", description="Buyer's urgency level"
    )
    bundle_skus: List[str] = Field(
        default_factory=list,
        description="List of additional SKUs requested as part of a bundle",
    )
    buyer_message: Optional[str] = Field(
        None, description="Optional raw text message or justification from buyer"
    )


class ProposedOfferLLMOutput(BaseModel):
    """Narrow Pydantic schema returned by the LLM.

    Security constraint:
    The model is only permitted to propose the price and draft justification.
    SKU and quantity are NEVER controlled or overridden by the LLM.
    """

    proposed_price: float = Field(
        ...,
        gt=0,
        description="Proposed unit counter-offer price in INR (must be positive)",
    )
    draft_justification: str = Field(
        ...,
        min_length=1,
        description="Clear, professional sales rationale explaining the proposed price to the buyer",
    )


class HistoricalRound(BaseModel):
    """Record of a past negotiation round including proposal and post-guardrail outcome."""

    round_number: int = Field(..., ge=0, description="Round number (0-indexed)")
    proposed_price: float = Field(..., gt=0, description="Proposed price in INR")
    quantity: int = Field(default=1, gt=0, description="Quantity")
    urgency: str = Field(default="normal", description="Urgency level")
    final_price: Optional[float] = Field(
        None, description="Final price after safety review by Guardrail Engine"
    )
    outcome_status: Optional[str] = Field(
        None,
        description="Summary of guardrail outcome (e.g. 'approved', 'clamped to floor', 'escalated for approval')",
    )
    blocking_rule: Optional[str] = Field(
        None, description="First rule that blocked/clamped the offer, if any"
    )
    deciding_rule: Optional[str] = Field(
        None, description="Rule that set the final price, if adjusted"
    )


class ProposedOffer(BaseModel):
    """The seller AI's proposed counter-offer generated by the Strategy Engine."""

    sku: str = Field(..., description="Target SKU identifier")
    proposed_price: float = Field(
        ..., gt=0, description="Proposed unit counter-offer price in INR"
    )
    quantity: int = Field(..., gt=0, description="Order quantity for this offer")
    round_number: int = Field(
        default=0, ge=0, description="Current negotiation round (0-indexed)"
    )
    draft_justification: str = Field(
        ...,
        description=(
            "Natural-language justification draft explaining the proposed price. "
            "Note: may be replaced by deterministic guardrail rationale downstream if clamped."
        ),
    )
    raw_model_response: Optional[str] = Field(
        None, description="Raw response text returned by the LLM for debugging/auditing"
    )
